### ISSUE TITLE
Shell commands should have help available

### ISSUE THREAD

**Issue by 27escape** [askucher/nixar#1]
If I install these on my system and forget where they came from, or other people were to use them on my system, then I/they have no idea how to run them

A basic help option to each command (-h) would be great even if it only points to the right place in the documentation webpage

Many thanks
kevin

**Comment by askucher** [comment]
Please try the `nixar` command

``` sh
$ nixar
```

You can check availability of nixar command in order to understand is it installed on your machine

Does it work for you?

BTW: There are some issues in documentation. Will fix them soon.

**Comment by 27escape** [comment]
Hi, thanks for the update.

However the issue still remains that individual commands have no help and other users of my system have no idea that the commands are from nixar and not built-ins.

Reducing surprises and 'delighting' users should also be one of the goals of your project.

Thanks for all your hard work so far, I like new ways of thinking of command line scripting.

kevin

**Comment by askucher** [comment]
Thank you. You provided good comments. 
I think all possible kinds of help should be there. already working on that.
