### ISSUE TITLE
Commands involving 'file' do not work

### ISSUE THREAD

**Issue by 27escape** [askucher/nixar#2]
For example 'fs all | file size ' (Recursively search for files and display their size)

I use linux and _size_ is not a valid parameter to the **file** command

Additionally, its best not to create new commands based on existing utilities (eg uniq) unless you are replicating their functionality (and bugs) exactly, otherwise this will lead to issues on systems where nixar is deployed with the nixar version potentially being used in scripts rather than the system default and breaking existing code - always a bad thing!

regards
kevin

**Comment by askucher** [comment]
The `file` command was replaced with `content` 

``` sh

fs "*.js" | content size  #=> file size
fs "*.js" | content modified #=> [modified] seconds ago
fs "*.js" | content lines  #=> prints file line by line

```

Yes. you are rights. uniq, col commands will be renamed to unique, cols.
`nixar` command shows entire list of available commands and will show the change log.
