### ISSUE TITLE
fs not returning filenames

### ISSUE THREAD

**Issue by paulirish** [askucher/nixar#4]
```
$ fs *.*
12372 bytes
111819 bytes
138845 bytes
232846 bytes
7043 bytes
19053 bytes
40226 bytes
312719 bytes
```

I have customized my `ls` command with an alias, so perhaps nixar is getting confused?

**Comment by askucher** [comment]
Will have not time to look right now but will fix very soon.

I use 'npm install glob' for that looks like issue came from here

**Comment by askucher** [comment]
```
npm remove nixar -g 
npm install nixar -g 
```

should fix this issue
